# Features
ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_LOCK_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

# Optimizations
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no
